FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN cat > /etc/nginx/conf.d/reverse-proxy.conf << 'EOF'
upstream app_backend {
    server app:5000;
}

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://app_backend;
    }
}
EOF

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
