apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: nginx-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-proxy-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-proxy
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
  - port: 80 # Internal port
    targetPort: 80
    nodePort: 30080 # External port
      # Default protocol is TCP